title: The Mythical Engineer
author: themythicalengineer@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Blog about Software Engineering

baseurl: ""
url: "https://themythicalengineer.com" # the base hostname & protocol for your site, e.g. http://example.com
backend: "https://themythicalengineer.herokuapp.com"
# backend: "http://localhost:5000"

twitter_username: _sks147
github_username:  sks147

permalink: /:year/:month/:day/:title.html

# Build settings

collections:
  authors:
    output: true

minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: _sks147
    github: sks147
    facebook: sks147
    instagram: _sks147

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima
plugins:
  - jekyll-feed

sass:
  style: compressed

collections:
  authors:
    output: true

header_pages:
  - authors.md

show_excerpts: false
google_analytics: UA-145053791-1

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
