version: '3.3'
services:
  jekyll:
    image: 'jekyll/jekyll:4.0'
    command: 'jekyll serve'
    ports:
      - '4000:4000'
    volumes:
      - '$PWD:/srv/jekyll'
      - '$PWD/vendor/bundle:/usr/local/bundle'
    environment:
      - JEKYLL_ENV=development