version: '3.3'
services:
  jekyll:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - '4000:4000'
    volumes:
      - '$PWD:/srv/jekyll'
      - '$PWD/vendor/bundle:/usr/local/bundle'
    environment:
      - JEKYLL_ENV=development