services:
  jekyll:
    build: .
    container_name: jekyll
    command: sh -c "bundle install && bundle exec jekyll serve --host 0.0.0.0 --force_polling --livereload"
    ports:
      - 4000:4000
      - 35729:35729
    volumes:
      - '.:/srv/jekyll'
      - bundle_cache:/usr/local/bundle
    environment:
      - JEKYLL_ENV=development

volumes:
  bundle_cache:
